### ISSUE TITLE
Dual resistances are missed

### ISSUE THREAD

**Issue by nexeh** [slikts/fetchpoeitems#2]
Good morning,

I tried your tool today and my resistances came out lower than what i had. what i found is that if a ring has a dual resist like this they are ignored. I know you haven't made changes to this in a long time but i thought id let you know know

![image](https://user-images.githubusercontent.com/2686591/95591647-92e4ef00-0a15-11eb-9546-19ecf0623ac8.png)
![image](https://user-images.githubusercontent.com/2686591/95591700-aabc7300-0a15-11eb-8054-e7ae530a54d8.png)

**Comment by nexeh** [comment]
Oh i just noticed crafted values are missed as well

**Comment by slikts** [comment]
I actually have no idea what this even is…

**Comment by slikts** [comment]
Thanks for the report, quite an odd experience to discover having made something with absolutely no recollection. 😄 I can't promise if I'll get around to fixing it, but I'll try.

**Comment by nexeh** [comment]
Hahaha, isnt that funny! I have done that before as well. Given that i resolved this in the PR ill go ahead and close this.
